/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 11-jun.-2024 12:14:59 p. m. 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

USE [dbEnvios]
GO

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TTarifas_TDestinos]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TTarifas] DROP CONSTRAINT [FK_TTarifas_TDestinos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TTarifas_TTiposCarga]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TTarifas] DROP CONSTRAINT [FK_TTarifas_TTiposCarga]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TEnvios_TClientes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TEnvios] DROP CONSTRAINT [FK_TEnvios_TClientes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TEnvios_TDestinos]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TEnvios] DROP CONSTRAINT [FK_TEnvios_TDestinos]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TClientes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TClientes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TDestinos]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TDestinos]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TTarifas]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TTarifas]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TTiposCarga]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TTiposCarga]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TEnvios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TEnvios]
GO

/* Create Tables */

CREATE TABLE [TClientes]
(
	[CI] nvarchar(20) NOT NULL,
	[Nombres] nvarchar(50) NOT NULL,
	[ApellidoPaterno] nvarchar(30) NULL,
	[ApellidoMaterno] nvarchar(30) NOT NULL,
	[Telefono] nvarchar(20) NOT NULL,
	[Direccion] text NULL
)
GO

CREATE TABLE [TDestinos]
(
	[Nombre] nvarchar(50) NOT NULL,
	[DestinoID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [TTarifas]
(
	[Costo] money NOT NULL,
	[Desccipcion] text NULL,
	[TipoID] int NULL,
	[TarifaID] int NOT NULL IDENTITY (1, 1),
	[DestinoID] int NULL
)
GO

CREATE TABLE [TTiposCarga]
(
	[Nombre] nvarchar(50) NOT NULL,
	[TipoID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [TEnvios]
(
	[EnviosID] int NOT NULL IDENTITY (1, 1),
	[Fecha] datetime NOT NULL,
	[Costo] money NOT NULL,
	[Detalle] nvarchar(max) NULL,
	[CI] nvarchar(20) NULL,
	[CI_destinatario] nvarchar(20) NULL,
	[DestinoID] int NULL,
	[Estado] nvarchar(10) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [TClientes] 
 ADD CONSTRAINT [PK_TClientes]
	PRIMARY KEY CLUSTERED ([CI] ASC)
GO

ALTER TABLE [TDestinos] 
 ADD CONSTRAINT [PK_TDestinos]
	PRIMARY KEY CLUSTERED ([DestinoID] ASC)
GO

ALTER TABLE [TDestinos] 
 ADD CONSTRAINT [IX_Nombre] UNIQUE NONCLUSTERED ([Nombre] ASC)
GO

ALTER TABLE [TTarifas] 
 ADD CONSTRAINT [PK_TTarifas]
	PRIMARY KEY CLUSTERED ([TarifaID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TTarifas_TDestinos] 
 ON [TTarifas] ([DestinoID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TTarifas_TTiposCarga] 
 ON [TTarifas] ([TipoID] ASC)
GO

ALTER TABLE [TTiposCarga] 
 ADD CONSTRAINT [PK_TTiposCarga]
	PRIMARY KEY CLUSTERED ([TipoID] ASC)
GO

ALTER TABLE [TTiposCarga] 
 ADD CONSTRAINT [IX_Nombre] UNIQUE NONCLUSTERED ([Nombre] ASC)
GO

ALTER TABLE [TEnvios] 
 ADD CONSTRAINT [PK_TEnvios]
	PRIMARY KEY CLUSTERED ([EnviosID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TEnvios_TClientes] 
 ON [TEnvios] ([CI] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TEnvios_TDestinos] 
 ON [TEnvios] ([DestinoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [TTarifas] ADD CONSTRAINT [FK_TTarifas_TDestinos]
	FOREIGN KEY ([DestinoID]) REFERENCES [TDestinos] ([DestinoID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [TTarifas] ADD CONSTRAINT [FK_TTarifas_TTiposCarga]
	FOREIGN KEY ([TipoID]) REFERENCES [TTiposCarga] ([TipoID]) ON DELETE Cascade ON UPDATE Cascade
GO

ALTER TABLE [TEnvios] ADD CONSTRAINT [FK_TEnvios_TClientes]
	FOREIGN KEY ([CI]) REFERENCES [TClientes] ([CI]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [TEnvios] ADD CONSTRAINT [FK_TEnvios_TDestinos]
	FOREIGN KEY ([DestinoID]) REFERENCES [TDestinos] ([DestinoID]) ON DELETE Cascade ON UPDATE Cascade
GO
